DM-44150: Remove explicit SdssShape dependency
lsst/meas_extensions_trailedSources pull request #20
Opened 2024-05-21 21:01 UTC by parejkoj

2024-05-22 17:06 UTC, bsmartradio commented on tests/test_trailedSources.py
I'm not sure why github isn't letting me select specific lines, but there are references to `base_SdssShape` throughout the test. Will these be left in until we refactor the tests?

2024-05-22 18:39 UTC, bsmartradio requested changes
The changes look fine, and the change in handling the length measurement is how I was going to change it. My only other comment is that there are a number of `SdssShape` references in both unit tests.

2024-05-22 18:39 UTC, bsmartradio commented on tests/test_trailedEdgeSources.py
There are references to `base_SdssShape` on lines 66, 169, 270, and 376 instead of `HSMShape`.

2024-05-22 22:15 UTC, parejkoj commented on tests/test_trailedSources.py
You can't comment on lines that aren't part of the PR, sadly.

With these changes, the trailed plugin is agnostic to which shape plug is used, so using SdssShape in the tests is fine. This also means that we don't have to add a dependency on meas_extensions_shapeHsm to this package, which is a good thing.

2024-05-22 22:16 UTC, parejkoj commented on tests/test_trailedEdgeSources.py
As I noted above, that's fine: trailed sources is now agnostic to which shape plugin was run, so we can use whatever is easiest in the tests.

2024-05-22 22:44 UTC, bsmartradio approved these changes
As said above, `SdssShape` can be used for the unit tests, so everything looks good.

2024-05-29 20:57 UTC, parejkoj commented
@bsmartradio : please take a look at the new test I added for you to expand on. I put in docstrings and refactored it to be easy to add new tests to, but let me know if anything there doesn't make sense.

2024-05-29 23:08 UTC, bsmartradio approved these changes
The new addition to the unit tests looks good.

2024-05-29 23:20 UTC, merged